"""empty message

Revision ID: 1c3c961cdb64
Revises: 63a624a32596
Create Date: 2021-07-16 14:49:48.650099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3c961cdb64'
down_revision = '63a624a32596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_flights', sa.Column('aircraft_name', sa.Text(), nullable=True))
    op.add_column('active_flights', sa.Column('aircraft_rego', sa.Text(), nullable=True))
    op.add_column('active_flights', sa.Column('altitude_agl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_flights', 'altitude_agl')
    op.drop_column('active_flights', 'aircraft_rego')
    op.drop_column('active_flights', 'aircraft_name')
    # ### end Alembic commands ###