"""empty message

Revision ID: 3560fb0f9bc0
Revises: e7a477af5448
Create Date: 2020-11-27 11:15:10.769882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3560fb0f9bc0'
down_revision = 'e7a477af5448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flightplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('alitude', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('FP__ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flightplan_id', sa.Integer(), nullable=False),
    sa.Column('rating_score', sa.Integer(), nullable=True),
    sa.Column('date_rated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flightplan_id'], ['flightplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flightplan__waypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flightplan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flightplan_id'], ['flightplan.id'], ),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flightplan__waypoints')
    op.drop_table('FP__ratings')
    op.drop_table('flightplan')
    # ### end Alembic commands ###
