"""empty message

Revision ID: 77c31d07e64d
Revises: 676eb5f9a2d6
Create Date: 2021-05-14 14:06:30.389591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c31d07e64d'
down_revision = '676eb5f9a2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goto_map_home_page', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'goto_map_home_page')
    # ### end Alembic commands ###
