"""empty message

Revision ID: 7d39e936e3fa
Revises: d5c463fee2c6
Create Date: 2021-03-25 13:18:47.064810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d39e936e3fa'
down_revision = 'd5c463fee2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_my_flights_check', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('volanta_export_path', sa.String(length=120), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'volanta_export_path')
    op.drop_column('user', 'show_my_flights_check')
    # ### end Alembic commands ###
