"""empty message

Revision ID: 8665781aedc7
Revises: 57fa99bf63ee
Create Date: 2020-11-27 09:51:29.389911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8665781aedc7'
down_revision = '57fa99bf63ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FP__ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fp_id', sa.Integer(), nullable=False),
    sa.Column('rating_score', sa.Integer(), nullable=True),
    sa.Column('date_rated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fp_id'], ['flightplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FP__ratings')
    # ### end Alembic commands ###
