"""empty message

Revision ID: 91fb8fb2a50b
Revises: 3033577bbeca
Create Date: 2021-06-28 16:11:48.587494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fb8fb2a50b'
down_revision = '3033577bbeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('altitude', sa.Integer(), nullable=False),
    sa.Column('heading_true', sa.Integer(), nullable=False),
    sa.Column('ias', sa.Integer(), nullable=False),
    sa.Column('ground_speed', sa.Integer(), nullable=False),
    sa.Column('show_checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_flights')
    # ### end Alembic commands ###
