"""empty message

Revision ID: e06b93a33f8b
Revises: d5c463fee2c6
Create Date: 2021-04-06 16:51:01.220286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06b93a33f8b'
down_revision = 'd5c463fee2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_flights',
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('aircraft_title', sa.Text(), nullable=False),
    sa.Column('aircraft_reg', sa.Text(), nullable=False),
    sa.Column('origin_name', sa.Text(), nullable=False),
    sa.Column('origin_icao', sa.Text(), nullable=False),
    sa.Column('destination_name', sa.Text(), nullable=False),
    sa.Column('destination_icao', sa.Text(), nullable=False),
    sa.Column('network', sa.Text(), nullable=False),
    sa.Column('flight_date', sa.DateTime(), nullable=False),
    sa.Column('real_flight_time', sa.Numeric(precision=8, scale=12), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('user_flight_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Text(), nullable=False),
    sa.Column('longitude', sa.Text(), nullable=False),
    sa.Column('altitude', sa.Text(), nullable=False),
    sa.Column('altitude_agl', sa.Text(), nullable=False),
    sa.Column('OnGround', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flightplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_flight_positions')
    op.drop_table('user_flights')
    # ### end Alembic commands ###
