"""empty message

Revision ID: e7a477af5448
Revises: b331aa9e1137
Create Date: 2020-10-23 02:27:52.560485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a477af5448'
down_revision = 'b331aa9e1137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flagged', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flagged', 'date_posted')
    # ### end Alembic commands ###
